// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nmx_c_nico.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NMX_Controller_Hello_FullMethodName                      = "/nmx_c.NMX_Controller/Hello"
	NMX_Controller_Subscribe_FullMethodName                  = "/nmx_c.NMX_Controller/Subscribe"
	NMX_Controller_FactoryReset_FullMethodName               = "/nmx_c.NMX_Controller/FactoryReset"
	NMX_Controller_GetStaticConfig_FullMethodName            = "/nmx_c.NMX_Controller/GetStaticConfig"
	NMX_Controller_SetStaticConfig_FullMethodName            = "/nmx_c.NMX_Controller/SetStaticConfig"
	NMX_Controller_GetAdminState_FullMethodName              = "/nmx_c.NMX_Controller/GetAdminState"
	NMX_Controller_SetAdminState_FullMethodName              = "/nmx_c.NMX_Controller/SetAdminState"
	NMX_Controller_GetDomainProperties_FullMethodName        = "/nmx_c.NMX_Controller/GetDomainProperties"
	NMX_Controller_GetDomainStateInfo_FullMethodName         = "/nmx_c.NMX_Controller/GetDomainStateInfo"
	NMX_Controller_GetTopologyInfo_FullMethodName            = "/nmx_c.NMX_Controller/GetTopologyInfo"
	NMX_Controller_GetComputeNodeCount_FullMethodName        = "/nmx_c.NMX_Controller/GetComputeNodeCount"
	NMX_Controller_GetComputeNodeLocationList_FullMethodName = "/nmx_c.NMX_Controller/GetComputeNodeLocationList"
	NMX_Controller_GetComputeNodeInfoList_FullMethodName     = "/nmx_c.NMX_Controller/GetComputeNodeInfoList"
	NMX_Controller_GetGpuInfoList_FullMethodName             = "/nmx_c.NMX_Controller/GetGpuInfoList"
	NMX_Controller_GetSwitchNodeCount_FullMethodName         = "/nmx_c.NMX_Controller/GetSwitchNodeCount"
	NMX_Controller_GetSwitchNodeLocationList_FullMethodName  = "/nmx_c.NMX_Controller/GetSwitchNodeLocationList"
	NMX_Controller_GetSwitchNodeInfoList_FullMethodName      = "/nmx_c.NMX_Controller/GetSwitchNodeInfoList"
	NMX_Controller_GetSwitchInfoList_FullMethodName          = "/nmx_c.NMX_Controller/GetSwitchInfoList"
	NMX_Controller_GetPartitionCount_FullMethodName          = "/nmx_c.NMX_Controller/GetPartitionCount"
	NMX_Controller_GetPartitionIdList_FullMethodName         = "/nmx_c.NMX_Controller/GetPartitionIdList"
	NMX_Controller_GetPartitionInfoList_FullMethodName       = "/nmx_c.NMX_Controller/GetPartitionInfoList"
	NMX_Controller_CreatePartition_FullMethodName            = "/nmx_c.NMX_Controller/CreatePartition"
	NMX_Controller_DeletePartition_FullMethodName            = "/nmx_c.NMX_Controller/DeletePartition"
	NMX_Controller_AddGpusToPartition_FullMethodName         = "/nmx_c.NMX_Controller/AddGpusToPartition"
	NMX_Controller_RemoveGpusFromPartition_FullMethodName    = "/nmx_c.NMX_Controller/RemoveGpusFromPartition"
	NMX_Controller_GetConnCount_FullMethodName               = "/nmx_c.NMX_Controller/GetConnCount"
	NMX_Controller_GetConnInfoList_FullMethodName            = "/nmx_c.NMX_Controller/GetConnInfoList"
	NMX_Controller_GetConnInfoCombined_FullMethodName        = "/nmx_c.NMX_Controller/GetConnInfoCombined"
	NMX_Controller_GetStateReport_FullMethodName             = "/nmx_c.NMX_Controller/GetStateReport"
)

// NMX_ControllerClient is the client API for NMX_Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// protolint:disable:next SERVICE_NAMES_UPPER_CAMEL_CASE
type NMX_ControllerClient interface {
	// Initial RPC call
	Hello(ctx context.Context, in *ClientHello, opts ...grpc.CallOption) (*ServerHello, error)
	// Client subscription for push notifications on updates
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerNotification], error)
	// Factory reset for state and configuration
	FactoryReset(ctx context.Context, in *FactoryResetRequest, opts ...grpc.CallOption) (*ReturnCode, error)
	// Get/Set static configuration
	GetStaticConfig(ctx context.Context, in *GetStaticConfigRequest, opts ...grpc.CallOption) (*StaticConfigResponse, error)
	SetStaticConfig(ctx context.Context, in *SetStaticConfigRequest, opts ...grpc.CallOption) (*ReturnCode, error)
	// AdminState management
	GetAdminState(ctx context.Context, in *GetAdminStateRequest, opts ...grpc.CallOption) (*GetAdminStateResponse, error)
	SetAdminState(ctx context.Context, in *SetAdminStateRequest, opts ...grpc.CallOption) (*SetAdminStateResponse, error)
	// GFM SDK APIs
	GetDomainProperties(ctx context.Context, in *GetDomainPropertiesRequest, opts ...grpc.CallOption) (*DomainProperties, error)
	GetDomainStateInfo(ctx context.Context, in *GetDomainStateInfoRequest, opts ...grpc.CallOption) (*DomainStateInfo, error)
	GetTopologyInfo(ctx context.Context, in *GetTopologyInfoRequest, opts ...grpc.CallOption) (*FmTopologyInfo, error)
	GetComputeNodeCount(ctx context.Context, in *GetComputeNodeCountRequest, opts ...grpc.CallOption) (*GetComputeNodeCountResponse, error)
	GetComputeNodeLocationList(ctx context.Context, in *GetComputeNodeLocationListRequest, opts ...grpc.CallOption) (*GetComputeNodeLocationListResponse, error)
	GetComputeNodeInfoList(ctx context.Context, in *GetComputeNodeInfoListRequest, opts ...grpc.CallOption) (*GetComputeNodeInfoListResponse, error)
	GetGpuInfoList(ctx context.Context, in *GetGpuInfoListRequest, opts ...grpc.CallOption) (*GetGpuInfoListResponse, error)
	GetSwitchNodeCount(ctx context.Context, in *GetSwitchNodeCountRequest, opts ...grpc.CallOption) (*GetSwitchNodeCountResponse, error)
	GetSwitchNodeLocationList(ctx context.Context, in *GetSwitchNodeLocationListRequest, opts ...grpc.CallOption) (*GetSwitchNodeLocationListResponse, error)
	GetSwitchNodeInfoList(ctx context.Context, in *GetSwitchNodeInfoListRequest, opts ...grpc.CallOption) (*GetSwitchNodeInfoListResponse, error)
	GetSwitchInfoList(ctx context.Context, in *GetSwitchInfoListRequest, opts ...grpc.CallOption) (*GetSwitchInfoListResponse, error)
	GetPartitionCount(ctx context.Context, in *GetPartitionCountRequest, opts ...grpc.CallOption) (*GetPartitionCountResponse, error)
	GetPartitionIdList(ctx context.Context, in *GetPartitionIdListRequest, opts ...grpc.CallOption) (*GetPartitionIdListResponse, error)
	GetPartitionInfoList(ctx context.Context, in *GetPartitionInfoListRequest, opts ...grpc.CallOption) (*GetPartitionInfoListResponse, error)
	CreatePartition(ctx context.Context, in *CreatePartitionRequest, opts ...grpc.CallOption) (*CreatePartitionResponse, error)
	DeletePartition(ctx context.Context, in *DeletePartitionRequest, opts ...grpc.CallOption) (*DeletePartitionResponse, error)
	AddGpusToPartition(ctx context.Context, in *UpdatePartitionRequest, opts ...grpc.CallOption) (*UpdatePartitionResponse, error)
	RemoveGpusFromPartition(ctx context.Context, in *UpdatePartitionRequest, opts ...grpc.CallOption) (*UpdatePartitionResponse, error)
	GetConnCount(ctx context.Context, in *GetConnCountRequest, opts ...grpc.CallOption) (*GetConnCountResponse, error)
	GetConnInfoList(ctx context.Context, in *GetConnInfoListRequest, opts ...grpc.CallOption) (*GetConnInfoListResponse, error)
	GetConnInfoCombined(ctx context.Context, in *GetConnInfoCombinedRequest, opts ...grpc.CallOption) (*ConnInfoCombined, error)
	// Get state reports
	GetStateReport(ctx context.Context, in *GetStateReportRequest, opts ...grpc.CallOption) (*GetStateReportResponse, error)
}

type nMX_ControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewNMX_ControllerClient(cc grpc.ClientConnInterface) NMX_ControllerClient {
	return &nMX_ControllerClient{cc}
}

func (c *nMX_ControllerClient) Hello(ctx context.Context, in *ClientHello, opts ...grpc.CallOption) (*ServerHello, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerHello)
	err := c.cc.Invoke(ctx, NMX_Controller_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerNotification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NMX_Controller_ServiceDesc.Streams[0], NMX_Controller_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, ServerNotification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NMX_Controller_SubscribeClient = grpc.ServerStreamingClient[ServerNotification]

func (c *nMX_ControllerClient) FactoryReset(ctx context.Context, in *FactoryResetRequest, opts ...grpc.CallOption) (*ReturnCode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, NMX_Controller_FactoryReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetStaticConfig(ctx context.Context, in *GetStaticConfigRequest, opts ...grpc.CallOption) (*StaticConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaticConfigResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_GetStaticConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) SetStaticConfig(ctx context.Context, in *SetStaticConfigRequest, opts ...grpc.CallOption) (*ReturnCode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReturnCode)
	err := c.cc.Invoke(ctx, NMX_Controller_SetStaticConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetAdminState(ctx context.Context, in *GetAdminStateRequest, opts ...grpc.CallOption) (*GetAdminStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminStateResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_GetAdminState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) SetAdminState(ctx context.Context, in *SetAdminStateRequest, opts ...grpc.CallOption) (*SetAdminStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAdminStateResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_SetAdminState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetDomainProperties(ctx context.Context, in *GetDomainPropertiesRequest, opts ...grpc.CallOption) (*DomainProperties, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainProperties)
	err := c.cc.Invoke(ctx, NMX_Controller_GetDomainProperties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetDomainStateInfo(ctx context.Context, in *GetDomainStateInfoRequest, opts ...grpc.CallOption) (*DomainStateInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainStateInfo)
	err := c.cc.Invoke(ctx, NMX_Controller_GetDomainStateInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetTopologyInfo(ctx context.Context, in *GetTopologyInfoRequest, opts ...grpc.CallOption) (*FmTopologyInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FmTopologyInfo)
	err := c.cc.Invoke(ctx, NMX_Controller_GetTopologyInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetComputeNodeCount(ctx context.Context, in *GetComputeNodeCountRequest, opts ...grpc.CallOption) (*GetComputeNodeCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetComputeNodeCountResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_GetComputeNodeCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetComputeNodeLocationList(ctx context.Context, in *GetComputeNodeLocationListRequest, opts ...grpc.CallOption) (*GetComputeNodeLocationListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetComputeNodeLocationListResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_GetComputeNodeLocationList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetComputeNodeInfoList(ctx context.Context, in *GetComputeNodeInfoListRequest, opts ...grpc.CallOption) (*GetComputeNodeInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetComputeNodeInfoListResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_GetComputeNodeInfoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetGpuInfoList(ctx context.Context, in *GetGpuInfoListRequest, opts ...grpc.CallOption) (*GetGpuInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGpuInfoListResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_GetGpuInfoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetSwitchNodeCount(ctx context.Context, in *GetSwitchNodeCountRequest, opts ...grpc.CallOption) (*GetSwitchNodeCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSwitchNodeCountResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_GetSwitchNodeCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetSwitchNodeLocationList(ctx context.Context, in *GetSwitchNodeLocationListRequest, opts ...grpc.CallOption) (*GetSwitchNodeLocationListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSwitchNodeLocationListResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_GetSwitchNodeLocationList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetSwitchNodeInfoList(ctx context.Context, in *GetSwitchNodeInfoListRequest, opts ...grpc.CallOption) (*GetSwitchNodeInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSwitchNodeInfoListResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_GetSwitchNodeInfoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetSwitchInfoList(ctx context.Context, in *GetSwitchInfoListRequest, opts ...grpc.CallOption) (*GetSwitchInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSwitchInfoListResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_GetSwitchInfoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetPartitionCount(ctx context.Context, in *GetPartitionCountRequest, opts ...grpc.CallOption) (*GetPartitionCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartitionCountResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_GetPartitionCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetPartitionIdList(ctx context.Context, in *GetPartitionIdListRequest, opts ...grpc.CallOption) (*GetPartitionIdListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartitionIdListResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_GetPartitionIdList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetPartitionInfoList(ctx context.Context, in *GetPartitionInfoListRequest, opts ...grpc.CallOption) (*GetPartitionInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartitionInfoListResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_GetPartitionInfoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) CreatePartition(ctx context.Context, in *CreatePartitionRequest, opts ...grpc.CallOption) (*CreatePartitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePartitionResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_CreatePartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) DeletePartition(ctx context.Context, in *DeletePartitionRequest, opts ...grpc.CallOption) (*DeletePartitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePartitionResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_DeletePartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) AddGpusToPartition(ctx context.Context, in *UpdatePartitionRequest, opts ...grpc.CallOption) (*UpdatePartitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePartitionResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_AddGpusToPartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) RemoveGpusFromPartition(ctx context.Context, in *UpdatePartitionRequest, opts ...grpc.CallOption) (*UpdatePartitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePartitionResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_RemoveGpusFromPartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetConnCount(ctx context.Context, in *GetConnCountRequest, opts ...grpc.CallOption) (*GetConnCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnCountResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_GetConnCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetConnInfoList(ctx context.Context, in *GetConnInfoListRequest, opts ...grpc.CallOption) (*GetConnInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnInfoListResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_GetConnInfoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetConnInfoCombined(ctx context.Context, in *GetConnInfoCombinedRequest, opts ...grpc.CallOption) (*ConnInfoCombined, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnInfoCombined)
	err := c.cc.Invoke(ctx, NMX_Controller_GetConnInfoCombined_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMX_ControllerClient) GetStateReport(ctx context.Context, in *GetStateReportRequest, opts ...grpc.CallOption) (*GetStateReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateReportResponse)
	err := c.cc.Invoke(ctx, NMX_Controller_GetStateReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NMX_ControllerServer is the server API for NMX_Controller service.
// All implementations should embed UnimplementedNMX_ControllerServer
// for forward compatibility.
//
// protolint:disable:next SERVICE_NAMES_UPPER_CAMEL_CASE
type NMX_ControllerServer interface {
	// Initial RPC call
	Hello(context.Context, *ClientHello) (*ServerHello, error)
	// Client subscription for push notifications on updates
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[ServerNotification]) error
	// Factory reset for state and configuration
	FactoryReset(context.Context, *FactoryResetRequest) (*ReturnCode, error)
	// Get/Set static configuration
	GetStaticConfig(context.Context, *GetStaticConfigRequest) (*StaticConfigResponse, error)
	SetStaticConfig(context.Context, *SetStaticConfigRequest) (*ReturnCode, error)
	// AdminState management
	GetAdminState(context.Context, *GetAdminStateRequest) (*GetAdminStateResponse, error)
	SetAdminState(context.Context, *SetAdminStateRequest) (*SetAdminStateResponse, error)
	// GFM SDK APIs
	GetDomainProperties(context.Context, *GetDomainPropertiesRequest) (*DomainProperties, error)
	GetDomainStateInfo(context.Context, *GetDomainStateInfoRequest) (*DomainStateInfo, error)
	GetTopologyInfo(context.Context, *GetTopologyInfoRequest) (*FmTopologyInfo, error)
	GetComputeNodeCount(context.Context, *GetComputeNodeCountRequest) (*GetComputeNodeCountResponse, error)
	GetComputeNodeLocationList(context.Context, *GetComputeNodeLocationListRequest) (*GetComputeNodeLocationListResponse, error)
	GetComputeNodeInfoList(context.Context, *GetComputeNodeInfoListRequest) (*GetComputeNodeInfoListResponse, error)
	GetGpuInfoList(context.Context, *GetGpuInfoListRequest) (*GetGpuInfoListResponse, error)
	GetSwitchNodeCount(context.Context, *GetSwitchNodeCountRequest) (*GetSwitchNodeCountResponse, error)
	GetSwitchNodeLocationList(context.Context, *GetSwitchNodeLocationListRequest) (*GetSwitchNodeLocationListResponse, error)
	GetSwitchNodeInfoList(context.Context, *GetSwitchNodeInfoListRequest) (*GetSwitchNodeInfoListResponse, error)
	GetSwitchInfoList(context.Context, *GetSwitchInfoListRequest) (*GetSwitchInfoListResponse, error)
	GetPartitionCount(context.Context, *GetPartitionCountRequest) (*GetPartitionCountResponse, error)
	GetPartitionIdList(context.Context, *GetPartitionIdListRequest) (*GetPartitionIdListResponse, error)
	GetPartitionInfoList(context.Context, *GetPartitionInfoListRequest) (*GetPartitionInfoListResponse, error)
	CreatePartition(context.Context, *CreatePartitionRequest) (*CreatePartitionResponse, error)
	DeletePartition(context.Context, *DeletePartitionRequest) (*DeletePartitionResponse, error)
	AddGpusToPartition(context.Context, *UpdatePartitionRequest) (*UpdatePartitionResponse, error)
	RemoveGpusFromPartition(context.Context, *UpdatePartitionRequest) (*UpdatePartitionResponse, error)
	GetConnCount(context.Context, *GetConnCountRequest) (*GetConnCountResponse, error)
	GetConnInfoList(context.Context, *GetConnInfoListRequest) (*GetConnInfoListResponse, error)
	GetConnInfoCombined(context.Context, *GetConnInfoCombinedRequest) (*ConnInfoCombined, error)
	// Get state reports
	GetStateReport(context.Context, *GetStateReportRequest) (*GetStateReportResponse, error)
}

// UnimplementedNMX_ControllerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNMX_ControllerServer struct{}

func (UnimplementedNMX_ControllerServer) Hello(context.Context, *ClientHello) (*ServerHello, error) {
	return nil, status.Error(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedNMX_ControllerServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[ServerNotification]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedNMX_ControllerServer) FactoryReset(context.Context, *FactoryResetRequest) (*ReturnCode, error) {
	return nil, status.Error(codes.Unimplemented, "method FactoryReset not implemented")
}
func (UnimplementedNMX_ControllerServer) GetStaticConfig(context.Context, *GetStaticConfigRequest) (*StaticConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStaticConfig not implemented")
}
func (UnimplementedNMX_ControllerServer) SetStaticConfig(context.Context, *SetStaticConfigRequest) (*ReturnCode, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStaticConfig not implemented")
}
func (UnimplementedNMX_ControllerServer) GetAdminState(context.Context, *GetAdminStateRequest) (*GetAdminStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminState not implemented")
}
func (UnimplementedNMX_ControllerServer) SetAdminState(context.Context, *SetAdminStateRequest) (*SetAdminStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAdminState not implemented")
}
func (UnimplementedNMX_ControllerServer) GetDomainProperties(context.Context, *GetDomainPropertiesRequest) (*DomainProperties, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDomainProperties not implemented")
}
func (UnimplementedNMX_ControllerServer) GetDomainStateInfo(context.Context, *GetDomainStateInfoRequest) (*DomainStateInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDomainStateInfo not implemented")
}
func (UnimplementedNMX_ControllerServer) GetTopologyInfo(context.Context, *GetTopologyInfoRequest) (*FmTopologyInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopologyInfo not implemented")
}
func (UnimplementedNMX_ControllerServer) GetComputeNodeCount(context.Context, *GetComputeNodeCountRequest) (*GetComputeNodeCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetComputeNodeCount not implemented")
}
func (UnimplementedNMX_ControllerServer) GetComputeNodeLocationList(context.Context, *GetComputeNodeLocationListRequest) (*GetComputeNodeLocationListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetComputeNodeLocationList not implemented")
}
func (UnimplementedNMX_ControllerServer) GetComputeNodeInfoList(context.Context, *GetComputeNodeInfoListRequest) (*GetComputeNodeInfoListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetComputeNodeInfoList not implemented")
}
func (UnimplementedNMX_ControllerServer) GetGpuInfoList(context.Context, *GetGpuInfoListRequest) (*GetGpuInfoListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGpuInfoList not implemented")
}
func (UnimplementedNMX_ControllerServer) GetSwitchNodeCount(context.Context, *GetSwitchNodeCountRequest) (*GetSwitchNodeCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSwitchNodeCount not implemented")
}
func (UnimplementedNMX_ControllerServer) GetSwitchNodeLocationList(context.Context, *GetSwitchNodeLocationListRequest) (*GetSwitchNodeLocationListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSwitchNodeLocationList not implemented")
}
func (UnimplementedNMX_ControllerServer) GetSwitchNodeInfoList(context.Context, *GetSwitchNodeInfoListRequest) (*GetSwitchNodeInfoListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSwitchNodeInfoList not implemented")
}
func (UnimplementedNMX_ControllerServer) GetSwitchInfoList(context.Context, *GetSwitchInfoListRequest) (*GetSwitchInfoListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSwitchInfoList not implemented")
}
func (UnimplementedNMX_ControllerServer) GetPartitionCount(context.Context, *GetPartitionCountRequest) (*GetPartitionCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPartitionCount not implemented")
}
func (UnimplementedNMX_ControllerServer) GetPartitionIdList(context.Context, *GetPartitionIdListRequest) (*GetPartitionIdListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPartitionIdList not implemented")
}
func (UnimplementedNMX_ControllerServer) GetPartitionInfoList(context.Context, *GetPartitionInfoListRequest) (*GetPartitionInfoListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPartitionInfoList not implemented")
}
func (UnimplementedNMX_ControllerServer) CreatePartition(context.Context, *CreatePartitionRequest) (*CreatePartitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePartition not implemented")
}
func (UnimplementedNMX_ControllerServer) DeletePartition(context.Context, *DeletePartitionRequest) (*DeletePartitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePartition not implemented")
}
func (UnimplementedNMX_ControllerServer) AddGpusToPartition(context.Context, *UpdatePartitionRequest) (*UpdatePartitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddGpusToPartition not implemented")
}
func (UnimplementedNMX_ControllerServer) RemoveGpusFromPartition(context.Context, *UpdatePartitionRequest) (*UpdatePartitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveGpusFromPartition not implemented")
}
func (UnimplementedNMX_ControllerServer) GetConnCount(context.Context, *GetConnCountRequest) (*GetConnCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnCount not implemented")
}
func (UnimplementedNMX_ControllerServer) GetConnInfoList(context.Context, *GetConnInfoListRequest) (*GetConnInfoListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnInfoList not implemented")
}
func (UnimplementedNMX_ControllerServer) GetConnInfoCombined(context.Context, *GetConnInfoCombinedRequest) (*ConnInfoCombined, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnInfoCombined not implemented")
}
func (UnimplementedNMX_ControllerServer) GetStateReport(context.Context, *GetStateReportRequest) (*GetStateReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStateReport not implemented")
}
func (UnimplementedNMX_ControllerServer) testEmbeddedByValue() {}

// UnsafeNMX_ControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NMX_ControllerServer will
// result in compilation errors.
type UnsafeNMX_ControllerServer interface {
	mustEmbedUnimplementedNMX_ControllerServer()
}

func RegisterNMX_ControllerServer(s grpc.ServiceRegistrar, srv NMX_ControllerServer) {
	// If the following call panics, it indicates UnimplementedNMX_ControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NMX_Controller_ServiceDesc, srv)
}

func _NMX_Controller_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientHello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).Hello(ctx, req.(*ClientHello))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NMX_ControllerServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, ServerNotification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NMX_Controller_SubscribeServer = grpc.ServerStreamingServer[ServerNotification]

func _NMX_Controller_FactoryReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactoryResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).FactoryReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_FactoryReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).FactoryReset(ctx, req.(*FactoryResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetStaticConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStaticConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetStaticConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetStaticConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetStaticConfig(ctx, req.(*GetStaticConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_SetStaticConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStaticConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).SetStaticConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_SetStaticConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).SetStaticConfig(ctx, req.(*SetStaticConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetAdminState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetAdminState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetAdminState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetAdminState(ctx, req.(*GetAdminStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_SetAdminState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAdminStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).SetAdminState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_SetAdminState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).SetAdminState(ctx, req.(*SetAdminStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetDomainProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDomainPropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetDomainProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetDomainProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetDomainProperties(ctx, req.(*GetDomainPropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetDomainStateInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDomainStateInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetDomainStateInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetDomainStateInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetDomainStateInfo(ctx, req.(*GetDomainStateInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetTopologyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopologyInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetTopologyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetTopologyInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetTopologyInfo(ctx, req.(*GetTopologyInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetComputeNodeCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComputeNodeCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetComputeNodeCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetComputeNodeCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetComputeNodeCount(ctx, req.(*GetComputeNodeCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetComputeNodeLocationList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComputeNodeLocationListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetComputeNodeLocationList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetComputeNodeLocationList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetComputeNodeLocationList(ctx, req.(*GetComputeNodeLocationListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetComputeNodeInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComputeNodeInfoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetComputeNodeInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetComputeNodeInfoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetComputeNodeInfoList(ctx, req.(*GetComputeNodeInfoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetGpuInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGpuInfoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetGpuInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetGpuInfoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetGpuInfoList(ctx, req.(*GetGpuInfoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetSwitchNodeCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwitchNodeCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetSwitchNodeCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetSwitchNodeCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetSwitchNodeCount(ctx, req.(*GetSwitchNodeCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetSwitchNodeLocationList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwitchNodeLocationListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetSwitchNodeLocationList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetSwitchNodeLocationList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetSwitchNodeLocationList(ctx, req.(*GetSwitchNodeLocationListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetSwitchNodeInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwitchNodeInfoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetSwitchNodeInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetSwitchNodeInfoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetSwitchNodeInfoList(ctx, req.(*GetSwitchNodeInfoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetSwitchInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwitchInfoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetSwitchInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetSwitchInfoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetSwitchInfoList(ctx, req.(*GetSwitchInfoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetPartitionCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartitionCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetPartitionCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetPartitionCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetPartitionCount(ctx, req.(*GetPartitionCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetPartitionIdList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartitionIdListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetPartitionIdList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetPartitionIdList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetPartitionIdList(ctx, req.(*GetPartitionIdListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetPartitionInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartitionInfoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetPartitionInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetPartitionInfoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetPartitionInfoList(ctx, req.(*GetPartitionInfoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_CreatePartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).CreatePartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_CreatePartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).CreatePartition(ctx, req.(*CreatePartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_DeletePartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).DeletePartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_DeletePartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).DeletePartition(ctx, req.(*DeletePartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_AddGpusToPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).AddGpusToPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_AddGpusToPartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).AddGpusToPartition(ctx, req.(*UpdatePartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_RemoveGpusFromPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).RemoveGpusFromPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_RemoveGpusFromPartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).RemoveGpusFromPartition(ctx, req.(*UpdatePartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetConnCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetConnCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetConnCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetConnCount(ctx, req.(*GetConnCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetConnInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnInfoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetConnInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetConnInfoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetConnInfoList(ctx, req.(*GetConnInfoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetConnInfoCombined_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnInfoCombinedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetConnInfoCombined(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetConnInfoCombined_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetConnInfoCombined(ctx, req.(*GetConnInfoCombinedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMX_Controller_GetStateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMX_ControllerServer).GetStateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMX_Controller_GetStateReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMX_ControllerServer).GetStateReport(ctx, req.(*GetStateReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NMX_Controller_ServiceDesc is the grpc.ServiceDesc for NMX_Controller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NMX_Controller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nmx_c.NMX_Controller",
	HandlerType: (*NMX_ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _NMX_Controller_Hello_Handler,
		},
		{
			MethodName: "FactoryReset",
			Handler:    _NMX_Controller_FactoryReset_Handler,
		},
		{
			MethodName: "GetStaticConfig",
			Handler:    _NMX_Controller_GetStaticConfig_Handler,
		},
		{
			MethodName: "SetStaticConfig",
			Handler:    _NMX_Controller_SetStaticConfig_Handler,
		},
		{
			MethodName: "GetAdminState",
			Handler:    _NMX_Controller_GetAdminState_Handler,
		},
		{
			MethodName: "SetAdminState",
			Handler:    _NMX_Controller_SetAdminState_Handler,
		},
		{
			MethodName: "GetDomainProperties",
			Handler:    _NMX_Controller_GetDomainProperties_Handler,
		},
		{
			MethodName: "GetDomainStateInfo",
			Handler:    _NMX_Controller_GetDomainStateInfo_Handler,
		},
		{
			MethodName: "GetTopologyInfo",
			Handler:    _NMX_Controller_GetTopologyInfo_Handler,
		},
		{
			MethodName: "GetComputeNodeCount",
			Handler:    _NMX_Controller_GetComputeNodeCount_Handler,
		},
		{
			MethodName: "GetComputeNodeLocationList",
			Handler:    _NMX_Controller_GetComputeNodeLocationList_Handler,
		},
		{
			MethodName: "GetComputeNodeInfoList",
			Handler:    _NMX_Controller_GetComputeNodeInfoList_Handler,
		},
		{
			MethodName: "GetGpuInfoList",
			Handler:    _NMX_Controller_GetGpuInfoList_Handler,
		},
		{
			MethodName: "GetSwitchNodeCount",
			Handler:    _NMX_Controller_GetSwitchNodeCount_Handler,
		},
		{
			MethodName: "GetSwitchNodeLocationList",
			Handler:    _NMX_Controller_GetSwitchNodeLocationList_Handler,
		},
		{
			MethodName: "GetSwitchNodeInfoList",
			Handler:    _NMX_Controller_GetSwitchNodeInfoList_Handler,
		},
		{
			MethodName: "GetSwitchInfoList",
			Handler:    _NMX_Controller_GetSwitchInfoList_Handler,
		},
		{
			MethodName: "GetPartitionCount",
			Handler:    _NMX_Controller_GetPartitionCount_Handler,
		},
		{
			MethodName: "GetPartitionIdList",
			Handler:    _NMX_Controller_GetPartitionIdList_Handler,
		},
		{
			MethodName: "GetPartitionInfoList",
			Handler:    _NMX_Controller_GetPartitionInfoList_Handler,
		},
		{
			MethodName: "CreatePartition",
			Handler:    _NMX_Controller_CreatePartition_Handler,
		},
		{
			MethodName: "DeletePartition",
			Handler:    _NMX_Controller_DeletePartition_Handler,
		},
		{
			MethodName: "AddGpusToPartition",
			Handler:    _NMX_Controller_AddGpusToPartition_Handler,
		},
		{
			MethodName: "RemoveGpusFromPartition",
			Handler:    _NMX_Controller_RemoveGpusFromPartition_Handler,
		},
		{
			MethodName: "GetConnCount",
			Handler:    _NMX_Controller_GetConnCount_Handler,
		},
		{
			MethodName: "GetConnInfoList",
			Handler:    _NMX_Controller_GetConnInfoList_Handler,
		},
		{
			MethodName: "GetConnInfoCombined",
			Handler:    _NMX_Controller_GetConnInfoCombined_Handler,
		},
		{
			MethodName: "GetStateReport",
			Handler:    _NMX_Controller_GetStateReport_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _NMX_Controller_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nmx_c_nico.proto",
}
