// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the MachineNetworkInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineNetworkInterface{}

// MachineNetworkInterface Describes information about an Ethernet Interface of a Machine
type MachineNetworkInterface struct {
	MacAddress  NullableString `json:"macAddress,omitempty"`
	Vendor      NullableString `json:"vendor,omitempty"`
	Device      NullableString `json:"device,omitempty"`
	Path        NullableString `json:"path,omitempty"`
	NumaNode    *int32         `json:"numaNode,omitempty"`
	Description NullableString `json:"description,omitempty"`
	Slot        NullableString `json:"slot,omitempty"`
	Lldp        *LLDP          `json:"lldp,omitempty"`
}

// NewMachineNetworkInterface instantiates a new MachineNetworkInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineNetworkInterface() *MachineNetworkInterface {
	this := MachineNetworkInterface{}
	return &this
}

// NewMachineNetworkInterfaceWithDefaults instantiates a new MachineNetworkInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineNetworkInterfaceWithDefaults() *MachineNetworkInterface {
	this := MachineNetworkInterface{}
	return &this
}

// GetMacAddress returns the MacAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineNetworkInterface) GetMacAddress() string {
	if o == nil || IsNil(o.MacAddress.Get()) {
		var ret string
		return ret
	}
	return *o.MacAddress.Get()
}

// GetMacAddressOk returns a tuple with the MacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineNetworkInterface) GetMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MacAddress.Get(), o.MacAddress.IsSet()
}

// HasMacAddress returns a boolean if a field has been set.
func (o *MachineNetworkInterface) HasMacAddress() bool {
	if o != nil && o.MacAddress.IsSet() {
		return true
	}

	return false
}

// SetMacAddress gets a reference to the given NullableString and assigns it to the MacAddress field.
func (o *MachineNetworkInterface) SetMacAddress(v string) {
	o.MacAddress.Set(&v)
}

// SetMacAddressNil sets the value for MacAddress to be an explicit nil
func (o *MachineNetworkInterface) SetMacAddressNil() {
	o.MacAddress.Set(nil)
}

// UnsetMacAddress ensures that no value is present for MacAddress, not even an explicit nil
func (o *MachineNetworkInterface) UnsetMacAddress() {
	o.MacAddress.Unset()
}

// GetVendor returns the Vendor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineNetworkInterface) GetVendor() string {
	if o == nil || IsNil(o.Vendor.Get()) {
		var ret string
		return ret
	}
	return *o.Vendor.Get()
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineNetworkInterface) GetVendorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vendor.Get(), o.Vendor.IsSet()
}

// HasVendor returns a boolean if a field has been set.
func (o *MachineNetworkInterface) HasVendor() bool {
	if o != nil && o.Vendor.IsSet() {
		return true
	}

	return false
}

// SetVendor gets a reference to the given NullableString and assigns it to the Vendor field.
func (o *MachineNetworkInterface) SetVendor(v string) {
	o.Vendor.Set(&v)
}

// SetVendorNil sets the value for Vendor to be an explicit nil
func (o *MachineNetworkInterface) SetVendorNil() {
	o.Vendor.Set(nil)
}

// UnsetVendor ensures that no value is present for Vendor, not even an explicit nil
func (o *MachineNetworkInterface) UnsetVendor() {
	o.Vendor.Unset()
}

// GetDevice returns the Device field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineNetworkInterface) GetDevice() string {
	if o == nil || IsNil(o.Device.Get()) {
		var ret string
		return ret
	}
	return *o.Device.Get()
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineNetworkInterface) GetDeviceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Device.Get(), o.Device.IsSet()
}

// HasDevice returns a boolean if a field has been set.
func (o *MachineNetworkInterface) HasDevice() bool {
	if o != nil && o.Device.IsSet() {
		return true
	}

	return false
}

// SetDevice gets a reference to the given NullableString and assigns it to the Device field.
func (o *MachineNetworkInterface) SetDevice(v string) {
	o.Device.Set(&v)
}

// SetDeviceNil sets the value for Device to be an explicit nil
func (o *MachineNetworkInterface) SetDeviceNil() {
	o.Device.Set(nil)
}

// UnsetDevice ensures that no value is present for Device, not even an explicit nil
func (o *MachineNetworkInterface) UnsetDevice() {
	o.Device.Unset()
}

// GetPath returns the Path field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineNetworkInterface) GetPath() string {
	if o == nil || IsNil(o.Path.Get()) {
		var ret string
		return ret
	}
	return *o.Path.Get()
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineNetworkInterface) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Path.Get(), o.Path.IsSet()
}

// HasPath returns a boolean if a field has been set.
func (o *MachineNetworkInterface) HasPath() bool {
	if o != nil && o.Path.IsSet() {
		return true
	}

	return false
}

// SetPath gets a reference to the given NullableString and assigns it to the Path field.
func (o *MachineNetworkInterface) SetPath(v string) {
	o.Path.Set(&v)
}

// SetPathNil sets the value for Path to be an explicit nil
func (o *MachineNetworkInterface) SetPathNil() {
	o.Path.Set(nil)
}

// UnsetPath ensures that no value is present for Path, not even an explicit nil
func (o *MachineNetworkInterface) UnsetPath() {
	o.Path.Unset()
}

// GetNumaNode returns the NumaNode field value if set, zero value otherwise.
func (o *MachineNetworkInterface) GetNumaNode() int32 {
	if o == nil || IsNil(o.NumaNode) {
		var ret int32
		return ret
	}
	return *o.NumaNode
}

// GetNumaNodeOk returns a tuple with the NumaNode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineNetworkInterface) GetNumaNodeOk() (*int32, bool) {
	if o == nil || IsNil(o.NumaNode) {
		return nil, false
	}
	return o.NumaNode, true
}

// HasNumaNode returns a boolean if a field has been set.
func (o *MachineNetworkInterface) HasNumaNode() bool {
	if o != nil && !IsNil(o.NumaNode) {
		return true
	}

	return false
}

// SetNumaNode gets a reference to the given int32 and assigns it to the NumaNode field.
func (o *MachineNetworkInterface) SetNumaNode(v int32) {
	o.NumaNode = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineNetworkInterface) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineNetworkInterface) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *MachineNetworkInterface) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *MachineNetworkInterface) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *MachineNetworkInterface) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *MachineNetworkInterface) UnsetDescription() {
	o.Description.Unset()
}

// GetSlot returns the Slot field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineNetworkInterface) GetSlot() string {
	if o == nil || IsNil(o.Slot.Get()) {
		var ret string
		return ret
	}
	return *o.Slot.Get()
}

// GetSlotOk returns a tuple with the Slot field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineNetworkInterface) GetSlotOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Slot.Get(), o.Slot.IsSet()
}

// HasSlot returns a boolean if a field has been set.
func (o *MachineNetworkInterface) HasSlot() bool {
	if o != nil && o.Slot.IsSet() {
		return true
	}

	return false
}

// SetSlot gets a reference to the given NullableString and assigns it to the Slot field.
func (o *MachineNetworkInterface) SetSlot(v string) {
	o.Slot.Set(&v)
}

// SetSlotNil sets the value for Slot to be an explicit nil
func (o *MachineNetworkInterface) SetSlotNil() {
	o.Slot.Set(nil)
}

// UnsetSlot ensures that no value is present for Slot, not even an explicit nil
func (o *MachineNetworkInterface) UnsetSlot() {
	o.Slot.Unset()
}

// GetLldp returns the Lldp field value if set, zero value otherwise.
func (o *MachineNetworkInterface) GetLldp() LLDP {
	if o == nil || IsNil(o.Lldp) {
		var ret LLDP
		return ret
	}
	return *o.Lldp
}

// GetLldpOk returns a tuple with the Lldp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineNetworkInterface) GetLldpOk() (*LLDP, bool) {
	if o == nil || IsNil(o.Lldp) {
		return nil, false
	}
	return o.Lldp, true
}

// HasLldp returns a boolean if a field has been set.
func (o *MachineNetworkInterface) HasLldp() bool {
	if o != nil && !IsNil(o.Lldp) {
		return true
	}

	return false
}

// SetLldp gets a reference to the given LLDP and assigns it to the Lldp field.
func (o *MachineNetworkInterface) SetLldp(v LLDP) {
	o.Lldp = &v
}

func (o MachineNetworkInterface) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineNetworkInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.MacAddress.IsSet() {
		toSerialize["macAddress"] = o.MacAddress.Get()
	}
	if o.Vendor.IsSet() {
		toSerialize["vendor"] = o.Vendor.Get()
	}
	if o.Device.IsSet() {
		toSerialize["device"] = o.Device.Get()
	}
	if o.Path.IsSet() {
		toSerialize["path"] = o.Path.Get()
	}
	if !IsNil(o.NumaNode) {
		toSerialize["numaNode"] = o.NumaNode
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Slot.IsSet() {
		toSerialize["slot"] = o.Slot.Get()
	}
	if !IsNil(o.Lldp) {
		toSerialize["lldp"] = o.Lldp
	}
	return toSerialize, nil
}

type NullableMachineNetworkInterface struct {
	value *MachineNetworkInterface
	isSet bool
}

func (v NullableMachineNetworkInterface) Get() *MachineNetworkInterface {
	return v.value
}

func (v *NullableMachineNetworkInterface) Set(val *MachineNetworkInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineNetworkInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineNetworkInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineNetworkInterface(val *MachineNetworkInterface) *NullableMachineNetworkInterface {
	return &NullableMachineNetworkInterface{value: val, isSet: true}
}

func (v NullableMachineNetworkInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineNetworkInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
