/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the LLDP type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLDP{}

// LLDP Link Layer Discovery Protocol information for a network interface
type LLDP struct {
	PortId           *string `json:"portId,omitempty"`
	SwitchId         *string `json:"switchId,omitempty"`
	SwitchSystemName *string `json:"switchSystemName,omitempty"`
}

// NewLLDP instantiates a new LLDP object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLDP() *LLDP {
	this := LLDP{}
	return &this
}

// NewLLDPWithDefaults instantiates a new LLDP object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLDPWithDefaults() *LLDP {
	this := LLDP{}
	return &this
}

// GetPortId returns the PortId field value if set, zero value otherwise.
func (o *LLDP) GetPortId() string {
	if o == nil || IsNil(o.PortId) {
		var ret string
		return ret
	}
	return *o.PortId
}

// GetPortIdOk returns a tuple with the PortId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLDP) GetPortIdOk() (*string, bool) {
	if o == nil || IsNil(o.PortId) {
		return nil, false
	}
	return o.PortId, true
}

// HasPortId returns a boolean if a field has been set.
func (o *LLDP) HasPortId() bool {
	if o != nil && !IsNil(o.PortId) {
		return true
	}

	return false
}

// SetPortId gets a reference to the given string and assigns it to the PortId field.
func (o *LLDP) SetPortId(v string) {
	o.PortId = &v
}

// GetSwitchId returns the SwitchId field value if set, zero value otherwise.
func (o *LLDP) GetSwitchId() string {
	if o == nil || IsNil(o.SwitchId) {
		var ret string
		return ret
	}
	return *o.SwitchId
}

// GetSwitchIdOk returns a tuple with the SwitchId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLDP) GetSwitchIdOk() (*string, bool) {
	if o == nil || IsNil(o.SwitchId) {
		return nil, false
	}
	return o.SwitchId, true
}

// HasSwitchId returns a boolean if a field has been set.
func (o *LLDP) HasSwitchId() bool {
	if o != nil && !IsNil(o.SwitchId) {
		return true
	}

	return false
}

// SetSwitchId gets a reference to the given string and assigns it to the SwitchId field.
func (o *LLDP) SetSwitchId(v string) {
	o.SwitchId = &v
}

// GetSwitchSystemName returns the SwitchSystemName field value if set, zero value otherwise.
func (o *LLDP) GetSwitchSystemName() string {
	if o == nil || IsNil(o.SwitchSystemName) {
		var ret string
		return ret
	}
	return *o.SwitchSystemName
}

// GetSwitchSystemNameOk returns a tuple with the SwitchSystemName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLDP) GetSwitchSystemNameOk() (*string, bool) {
	if o == nil || IsNil(o.SwitchSystemName) {
		return nil, false
	}
	return o.SwitchSystemName, true
}

// HasSwitchSystemName returns a boolean if a field has been set.
func (o *LLDP) HasSwitchSystemName() bool {
	if o != nil && !IsNil(o.SwitchSystemName) {
		return true
	}

	return false
}

// SetSwitchSystemName gets a reference to the given string and assigns it to the SwitchSystemName field.
func (o *LLDP) SetSwitchSystemName(v string) {
	o.SwitchSystemName = &v
}

func (o LLDP) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLDP) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PortId) {
		toSerialize["portId"] = o.PortId
	}
	if !IsNil(o.SwitchId) {
		toSerialize["switchId"] = o.SwitchId
	}
	if !IsNil(o.SwitchSystemName) {
		toSerialize["switchSystemName"] = o.SwitchSystemName
	}
	return toSerialize, nil
}

type NullableLLDP struct {
	value *LLDP
	isSet bool
}

func (v NullableLLDP) Get() *LLDP {
	return v.value
}

func (v *NullableLLDP) Set(val *LLDP) {
	v.value = val
	v.isSet = true
}

func (v NullableLLDP) IsSet() bool {
	return v.isSet
}

func (v *NullableLLDP) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLDP(val *LLDP) *NullableLLDP {
	return &NullableLLDP{value: val, isSet: true}
}

func (v NullableLLDP) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLDP) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
