// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the LLDP type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLDP{}

// LLDP Link Layer Discovery Protocol information for a network interface
type LLDP struct {
	Name       *string `json:"name,omitempty"`
	Id         *string `json:"id,omitempty"`
	LocalPort  *string `json:"localPort,omitempty"`
	RemotePort *string `json:"remotePort,omitempty"`
}

// NewLLDP instantiates a new LLDP object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLDP() *LLDP {
	this := LLDP{}
	return &this
}

// NewLLDPWithDefaults instantiates a new LLDP object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLDPWithDefaults() *LLDP {
	this := LLDP{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LLDP) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLDP) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LLDP) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LLDP) SetName(v string) {
	o.Name = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LLDP) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLDP) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LLDP) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *LLDP) SetId(v string) {
	o.Id = &v
}

// GetLocalPort returns the LocalPort field value if set, zero value otherwise.
func (o *LLDP) GetLocalPort() string {
	if o == nil || IsNil(o.LocalPort) {
		var ret string
		return ret
	}
	return *o.LocalPort
}

// GetLocalPortOk returns a tuple with the LocalPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLDP) GetLocalPortOk() (*string, bool) {
	if o == nil || IsNil(o.LocalPort) {
		return nil, false
	}
	return o.LocalPort, true
}

// HasLocalPort returns a boolean if a field has been set.
func (o *LLDP) HasLocalPort() bool {
	if o != nil && !IsNil(o.LocalPort) {
		return true
	}

	return false
}

// SetLocalPort gets a reference to the given string and assigns it to the LocalPort field.
func (o *LLDP) SetLocalPort(v string) {
	o.LocalPort = &v
}

// GetRemotePort returns the RemotePort field value if set, zero value otherwise.
func (o *LLDP) GetRemotePort() string {
	if o == nil || IsNil(o.RemotePort) {
		var ret string
		return ret
	}
	return *o.RemotePort
}

// GetRemotePortOk returns a tuple with the RemotePort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLDP) GetRemotePortOk() (*string, bool) {
	if o == nil || IsNil(o.RemotePort) {
		return nil, false
	}
	return o.RemotePort, true
}

// HasRemotePort returns a boolean if a field has been set.
func (o *LLDP) HasRemotePort() bool {
	if o != nil && !IsNil(o.RemotePort) {
		return true
	}

	return false
}

// SetRemotePort gets a reference to the given string and assigns it to the RemotePort field.
func (o *LLDP) SetRemotePort(v string) {
	o.RemotePort = &v
}

func (o LLDP) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLDP) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LocalPort) {
		toSerialize["localPort"] = o.LocalPort
	}
	if !IsNil(o.RemotePort) {
		toSerialize["remotePort"] = o.RemotePort
	}
	return toSerialize, nil
}

type NullableLLDP struct {
	value *LLDP
	isSet bool
}

func (v NullableLLDP) Get() *LLDP {
	return v.value
}

func (v *NullableLLDP) Set(val *LLDP) {
	v.value = val
	v.isSet = true
}

func (v NullableLLDP) IsSet() bool {
	return v.isSet
}

func (v *NullableLLDP) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLDP(val *LLDP) *NullableLLDP {
	return &NullableLLDP{value: val, isSet: true}
}

func (v NullableLLDP) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLDP) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
